name: CI/CD Cypress Tests

on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20  

      - name: Install dependencies
        run: npm install

      - name: Installer serve et wait-on globalement
        run: |
          npm install -g serve wait-on

      - name: Start local server
        run: serve -s . -l 8080 &

      - name: Wait for server
        run: wait-on http://localhost:8080

      - name: Run Cypress Tests
        run: npm run test
        env:
          CYPRESS_baseUrl: http://localhost:8080